name: Mogan Preflight

on:
  workflow_dispatch:
    inputs:
      mogan_version:
        type: choice
        description: "Mogan Version"
        required: true
        options:
          - v1.2.0

env:
  XMAKE_ROOT: y

jobs:
  preflight:
    container: archlinux:base-devel
    runs-on: ubuntu-latest
    steps:
      - if: github.event.inputs.mogan_version == 'v1.2.0'
        name: System
        run: |
          sudo pacman -Syyu --noconfirm --needed
          sudo pacman -S --noconfirm --needed git xmake
          sudo pacman -S --noconfirm --needed qt5-base qt5-svg sqlite zlib curl texlive-core python libxext unzip

      - if: github.event.inputs.mogan_version == 'v1.2.0'
        name: Inspect
        run: |
          uname -a
          xmake --version
          gcc --version

      - if: github.event.inputs.mogan_version == 'v1.2.0'
        name: Checkout
        run: |
          git clone https://github.com/XmacsLabs/mogan
          cd mogan
          git submodule update --init
          git fetch --all --tags
          git checkout v1.2.0

      - if: github.event.inputs.mogan_version == 'v1.2.0'
        name: Build
        working-directory: mogan
        run: |
          xmake repo --update --yes
          xmake config -vD --policies=build.ccache -m releasedbg --yes
          xmake build --yes -vD research
