name: Mogan Yay

on:
  workflow_dispatch:
  
env:
  XMAKE_ROOT: y

jobs:
  preflight:
    container: archlinux:base-devel
    runs-on: ubuntu-latest
    steps:
    - name: System
      run: |
        sudo pacman -Syyu --noconfirm --needed
        sudo pacman -S --noconfirm --needed git xmake
        sudo pacman -S --noconfirm --needed qt5-base qt5-svg sqlite zlib curl texlive-core python libxext unzip libgit2

    - name: Inspect
      run: |
        uname -a
        xmake --version
        gcc --version

    - name: Yay
      run: |
        pacman -S --needed base-devel
        git clone https://aur.archlinux.org/yay.git
        cd yay
        makepkg -si

    - name: Mogan
      run: |
        yay
        yay -S mogan
