name: Mogan Yay

on:
  workflow_dispatch:
  
env:
  XMAKE_ROOT: y

jobs:
  preflight:
    container: archlinux:base-devel
    runs-on: ubuntu-latest
    steps:
    - name: System
      run: |
        sudo pacman -Syyu --noconfirm --needed
        sudo pacman -S --noconfirm --needed git xmake
        sudo pacman -S --noconfirm --needed qt5-base qt5-svg sqlite zlib curl texlive-core python libxext unzip libgit2

    - name: Inspect
      run: |
        uname -a
        xmake --version
        gcc --version

    - name: Yay
      run: |
        # https://github.com/edlanglois/pkgbuild-action/blob/master/entrypoint.sh

        # Makepkg does not allow running as root
        # Create a new user `builder`
        # `builder` needs to have a home directory because some PKGBUILDs will try to
        # write to it (e.g. for cache)
        useradd builder -m
        # When installing dependencies, makepkg will use sudo
        # Give user `builder` passwordless sudo access
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        
        # Give all users (particularly builder) full access to these files
        chmod -R a+rw .
        
        git clone https://aur.archlinux.org/yay.git
        cd yay
        sudo -H -u builder makepkg -si

    - name: Mogan
      run: |
        sudo -H -u builder yay
        sudo -H -u builder yay -S mogan
